In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
df['class'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

Petal Length의 회귀 곡선

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score

In [12]:
X = df.iloc[:,[0,1,3,4]].values
y = df.iloc[:,2].values

In [13]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2021
)

In [14]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [15]:
pred = lr.predict(X_test)

In [16]:
from sklearn.metrics import r2_score, mean_squared_error
mse = mean_squared_error(y_test, pred)
rmse = np.sqrt(mse)
print(f'Mean Squared Error: {mse:.4f}, RMSE: {rmse:.4f}')

Mean Squared Error: 0.0981, RMSE: 0.3132


In [17]:
score = r2_score(y_test, pred)
print(f'R_squared: {score:.4f}')

R_squared: 0.9682


In [19]:
lr.coef_

array([ 0.68227323, -0.51925158,  1.11668415,  0.37500635])

In [20]:
lr.intercept_

-0.36699949396033205

교차 검증 - cross_val_score

In [22]:
# pl = 0.682sl - 0.519sw + 1.116pw + 0.375cl -0.366

In [23]:
from sklearn.model_selection import cross_val_score
lr = LinearRegression()

In [26]:
# 5 폴드 세트로 MSE를 구함
neg_mean_scores = cross_val_score(lr, X, y,
                                 scoring='neg_mean_squared_error', cv=5)
rmse_scores = np.sqrt(-neg_mean_scores)
avg_rmse = np.average(rmse_scores)

print('개별 MSE:', np.round(neg_mean_scores,2))
print('개별 RMSE:', np.round(rmse_scores,2))
print(f'평균 RMSE: {avg_rmse:.4f}')

개별 MSE: [-0.06 -0.08 -0.14 -0.1  -0.21]
개별 RMSE: [0.25 0.28 0.38 0.32 0.46]
평균 RMSE: 0.3387


Petal Width에 대한 회귀식 만들기

In [27]:
X = df.iloc[:,[0,1,2,4]].values
y = df.iloc[:,3].values
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2021
)
lr = LinearRegression()
lr.fit(X_train, y_train)
pred = lr.predict(X_test)
mse = mean_squared_error(y_test, pred)
r2 = r2_score(y_test, pred)
print(f'MSE: {mse:.2f}, RMSE: {np.sqrt(mse):.2f}')
print(f'R_squared: {r2:.4f}')

MSE: 0.04, RMSE: 0.19
R_squared: 0.9226


In [28]:
lr.coef_

array([-0.12876754,  0.17861614,  0.32741898,  0.37562097])

In [29]:
lr.intercept_

-0.1944501604164237

In [30]:
# 회계식:pw = -0.128sl + 0.178sw + 0.327pl + 0.375cl - 0.194

In [31]:
# 5 폴드 세트로 MSE를 구함
neg_mean_scores = cross_val_score(lr, X, y,
                                scoring='neg_mean_squared_error', cv=5)
rmse_scores = np.sqrt(-neg_mean_scores)
avg_rmse = np.average(rmse_scores)

print('개별 MSE: ',np.round(neg_mean_scores,2))
print('개별 RMSE: ',np.round(rmse_scores,2))
print(f'평균 RMSE: {avg_rmse:.4f}')

개별 MSE:  [-0.01 -0.02 -0.02 -0.04 -0.07]
개별 RMSE:  [0.09 0.14 0.15 0.19 0.26]
평균 RMSE: 0.1667


Sepal Length

In [32]:
X = df.iloc[:,[1,2,3,4]].values
y = df.iloc[:,0].values
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2021
)
lr = LinearRegression()
lr.fit(X_train, y_train)
pred = lr.predict(X_test)
mse = mean_squared_error(y_test, pred)
r2 = r2_score(y_test, pred)
print(f'MSE: {mse:.2f}, RMSE: {np.sqrt(mse):.2f}')
print(f'R_squared: {r2:.4f}')

MSE: 0.07, RMSE: 0.27
R_squared: 0.8808


In [33]:
lr.coef_ ,lr.intercept_

(array([ 0.60733316,  0.77406606, -0.49825608, -0.21265098]),
 1.9046012133683519)

In [34]:
# sl = 0.607sw +0.774pl -0.498pw-0.212cl +1.904

In [35]:
# 5 폴드 세트로 MSE를 구함
neg_mean_scores = cross_val_score(lr, X, y,
                                scoring='neg_mean_squared_error', cv=5)
rmse_scores = np.sqrt(-neg_mean_scores)
avg_rmse = np.average(rmse_scores)

print('개별 MSE: ',np.round(neg_mean_scores,2))
print('개별 RMSE: ',np.round(rmse_scores,2))
print(f'평균 RMSE: {avg_rmse:.4f}')

개별 MSE:  [-0.06 -0.08 -0.14 -0.1  -0.14]
개별 RMSE:  [0.25 0.29 0.37 0.31 0.38]
평균 RMSE: 0.3199


SW 구하기

In [43]:
X = df.iloc[:,[0,2,3,4]].values
y = df.iloc[:,1].values
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2021
)
lr = LinearRegression()
lr.fit(X_train, y_train)
pred = lr.predict(X_test)
mse = mean_squared_error(y_test, pred)
r2 = r2_score(y_test, pred)
print(f'MSE: {mse:.2f}, RMSE: {np.sqrt(mse):.2f}')
print(f'R_squared: {r2:.4f}')

MSE: 0.05, RMSE: 0.22
R_squared: 0.5667


In [44]:
lr.coef_ ,lr.intercept_

(array([ 0.61339502, -0.59499152,  0.69803975, -0.12580651]),
 0.9976767818176975)

In [45]:
# sw =0.613sl -0.594pl +0.698pw -0.125cl +0.pp7

In [46]:
# 5 폴드 세트로 MSE를 구함
neg_mean_scores = cross_val_score(lr, X, y,
                                scoring='neg_mean_squared_error', cv=5)
rmse_scores = np.sqrt(-neg_mean_scores)
avg_rmse = np.average(rmse_scores)

print('개별 MSE: ',np.round(neg_mean_scores,2))
print('개별 RMSE: ',np.round(rmse_scores,2))
print(f'평균 RMSE: {avg_rmse:.4f}')

개별 MSE:  [-0.08 -0.11 -0.16 -0.08 -0.11]
개별 RMSE:  [0.28 0.33 0.41 0.29 0.33]
평균 RMSE: 0.3289


In [53]:
fig, asx = plt.subplots(figsize=(16,8))
lm_features = ['sepal length','sepal width','petal width','class']

for i, feature in enumerate(lm_features):
    
    sns.regplot(x=feature, y='petal length', data=df)

KeyError: 'sepal length'

In [ ]:
# df = df.rename({'sepal length (cm)':'SL', 'sepal width (cm)':'SW', 'petal length (cm)':'PL', 'petal width (cm)':'PW'}, axis='columns')
# df.head()
# X = df[['SL', 'SW', 'PW', 'C']]
# y = df['PL']
# 이런식으로 컬럼을 정리해서 하면 보기 쉽잖아 ㅋㅋ